import Footer from '@/components/parts/Footer'
import Header from '@/components/parts/Header'
import ReactQueryProvider from '@/providers/ReactQuery'
import ToastProvider from '@/providers/Toaster'
import { Nanum_Gothic } from 'next/font/google'
import './globals.scss'

const nanumGothic = Nanum_Gothic({ subsets: ['latin'], weight: ['400', '700', '800'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nanumGothic.className}>
        <ReactQueryProvider>
          <div className='flex flex-col justify-between h-screen'>
            <Header></Header>
            <main className='pt-70pxr'>{children}</main>
            <Footer></Footer>
          </div>
        </ReactQueryProvider>
        <ToastProvider></ToastProvider>
        <div id='tooltips'></div>
      </body>
    </html>
  )
}
