import ReactQueryProvider from '@/providers/ReactQuery'
import ToastProvider from '@/providers/Toaster'
import './globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <ToastProvider></ToastProvider>
      </body>
    </html>
  )
}
